Repository fabric-testbed/fabrictestbed-extensions, pull requests merged in 2023-08, with the labels that each got.

#218 Address warnings when running sphinx-build
  fabrictestbed_extensions/fablib/fablib.py
  fabrictestbed_extensions/fablib/node.py
  fabrictestbed_extensions/fablib/slice.py
  tox.ini
Labels: documentation, no changelog

#220 Format docstrings
  CHANGELOG.md
  docs/source/component.rst
  docs/source/fablib.rst
  docs/source/facility_port.rst
  docs/source/interface.rst
  docs/source/network_service.rst
  docs/source/node.rst
  docs/source/resources.rst
  docs/source/slice.rst
  fabrictestbed_extensions/fablib/facility_port.py
  fabrictestbed_extensions/fablib/network_service.py
  fabrictestbed_extensions/fablib/node.py
  fabrictestbed_extensions/fablib/slice.py
Labels: documentation

#226 update fim dependencies
  fabrictestbed_extensions/__init__.py
  pyproject.toml
Labels: no changelog

#230 Getter optimization
  CHANGELOG.md
  fabrictestbed_extensions/__init__.py
  fabrictestbed_extensions/fablib/fablib.py
  fabrictestbed_extensions/fablib/resources.py
  pyproject.toml
Labels: bug, enhancement
